In [2]:
import pandas as pd
mdf = pd.read_csv('linked_mortality_file_1999_2000.csv') # Load mortality file
print( mdf.head() )
gdf = pd.read_sas("DEMO.xpt", format="xport") # Load demographics file
print( gdf.head() )
df = gdf.merge(mdf, on="SEQN", how="inner") # Merge mortality and demographics on SEQN variable

   SEQN  ELIGSTAT  MORTSTAT  UCOD_LEADING  DIABETES  HYPERTEN  PERMTH_INT  \
0     1         2       NaN           NaN       NaN       NaN         NaN
1     2         1       1.0           6.0       0.0       0.0       177.0
2     3         2       NaN           NaN       NaN       NaN         NaN
3     4         2       NaN           NaN       NaN       NaN         NaN
4     5         1       0.0           NaN       NaN       NaN       244.0

   PERMTH_EXM
0         NaN
1       177.0
2         NaN
3         NaN
4       244.0
   SEQN  SDDSRVYR  RIDSTATR  RIDEXMON  RIAGENDR  RIDAGEYR  RIDAGEMN  RIDAGEEX  \
0   1.0       1.0       2.0       2.0       2.0       2.0      29.0      31.0
1   2.0       1.0       2.0       2.0       1.0      77.0     926.0     926.0
2   3.0       1.0       2.0       1.0       2.0      10.0     125.0     126.0
3   4.0       1.0       2.0       2.0       1.0       1.0      22.0      23.0
4   5.0       1.0       2.0       2.0       1.0      49.0     597.0     597.0

   RIDRETH1  RIDRETH2  ...      WTIREP43      WTIREP44      WTIREP45  \
0       4.0       2.0  ...  10094.017100   9912.461855   9727.078709
1       3.0       1.0  ...  27186.728682  27324.345051  28099.663528
2       3.0       1.0  ...  43993.193099  44075.386428  46642.563799
3       4.0       2.0  ...  10702.307249  10531.444441  10346.119327
4       3.0       1.0  ...  93164.782430  92119.608772  95388.490406

       WTIREP46      WTIREP47      WTIREP48      WTIREP49      WTIREP50  \
0  10041.524113  9.953956e+03   9857.381983   9865.152486  10327.992682
1  27757.066921  2.804929e+04  26716.602006  26877.704909  27268.025234
2  44967.681579  4.457248e+04  44087.945688  44831.370881  44480.987235
3  10636.063039  5.397605e-79  10533.108939  10654.749584  10851.024385
4  94131.383538  9.529781e+04  91325.082461  91640.586117  92817.926915

       WTIREP51      WTIREP52
0   9809.165049  10323.315747
1  27406.383620  26984.812909
2  45389.112766  43781.905637
3  10564.981435  11012.529729
4  94282.855382  91993.251203

[5 rows x 144 columns]

In [3]:
df.head()

,SEQN,SDDSRVYR,RIDSTATR,RIDEXMON,RIAGENDR,RIDAGEYR,RIDAGEMN,RIDAGEEX,RIDRETH1,RIDRETH2,...,WTIREP50,WTIREP51,WTIREP52,ELIGSTAT,MORTSTAT,UCOD_LEADING,DIABETES,HYPERTEN,PERMTH_INT,PERMTH_EXM
0,1.0,1.0,2.0,2.0,2.0,2.0,29.0,31.0,4.0,2.0,...,10327.992682,9809.165049,10323.315747,2,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,1.0,2.0,2.0,1.0,77.0,926.0,926.0,3.0,1.0,...,27268.025234,27406.383620,26984.812909,1,1.0,6.0,0.0,0.0,177.0,177.0
2,3.0,1.0,2.0,1.0,2.0,10.0,125.0,126.0,3.0,1.0,...,44480.987235,45389.112766,43781.905637,2,NaN,NaN,NaN,NaN,NaN,NaN
3,4.0,1.0,2.0,2.0,1.0,1.0,22.0,23.0,4.0,2.0,...,10851.024385,10564.981435,11012.529729,2,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,1.0,2.0,2.0,1.0,49.0,597.0,597.0,3.0,1.0,...,92817.926915,94282.855382,91993.251203,1,0.0,NaN,NaN,NaN,244.0,244.0

In [4]:
df.columns

Index(['SEQN', 'SDDSRVYR', 'RIDSTATR', 'RIDEXMON', 'RIAGENDR', 'RIDAGEYR',
       'RIDAGEMN', 'RIDAGEEX', 'RIDRETH1', 'RIDRETH2',
       ...
       'WTIREP50', 'WTIREP51', 'WTIREP52', 'ELIGSTAT', 'MORTSTAT',
       'UCOD_LEADING', 'DIABETES', 'HYPERTEN', 'PERMTH_INT', 'PERMTH_EXM'],
      dtype='object', length=151)

In [5]:
caffeine_df = pd.read_csv("SSCAFE_A.csv")

In [6]:
df.to_csv("merged_mortality_demographics.csv", index=False) # Save merged file to CSV

In [7]:
everything = df.merge(caffeine_df, on="SEQN", how="inner")

In [8]:
df.columns.tolist()

['SEQN',
 'SDDSRVYR',
 'RIDSTATR',
 'RIDEXMON',
 'RIAGENDR',
 'RIDAGEYR',
 'RIDAGEMN',
 'RIDAGEEX',
 'RIDRETH1',
 'RIDRETH2',
 'DMQMILIT',
 'DMDBORN',
 'DMDCITZN',
 'DMDYRSUS',
 'DMDEDUC3',
 'DMDEDUC2',
 'DMDEDUC',
 'DMDSCHOL',
 'DMDMARTL',
 'DMDHHSIZ',
 'INDHHINC',
 'INDFMINC',
 'INDFMPIR',
 'RIDEXPRG',
 'RIDPREG',
 'DMDHRGND',
 'DMDHRAGE',
 'DMDHRBRN',
 'DMDHREDU',
 'DMDHRMAR',
 'DMDHSEDU',
 'WTINT2YR',
 'WTINT4YR',
 'WTMEC2YR',
 'WTMEC4YR',
 'SDMVPSU',
 'SDMVSTRA',
 'SDJ1REPN',
 'DMAETHN',
 'DMARACE',
 'WTMREP01',
 'WTMREP02',
 'WTMREP03',
 'WTMREP04',
 'WTMREP05',
 'WTMREP06',
 'WTMREP07',
 'WTMREP08',
 'WTMREP09',
 'WTMREP10',
 'WTMREP11',
 'WTMREP12',
 'WTMREP13',
 'WTMREP14',
 'WTMREP15',
 'WTMREP16',
 'WTMREP17',
 'WTMREP18',
 'WTMREP19',
 'WTMREP20',
 'WTMREP21',
 'WTMREP22',
 'WTMREP23',
 'WTMREP24',
 'WTMREP25',
 'WTMREP26',
 'WTMREP27',
 'WTMREP28',
 'WTMREP29',
 'WTMREP30',
 'WTMREP31',
 'WTMREP32',
 'WTMREP33',
 'WTMREP34',
 'WTMREP35',
 'WTMREP36',
 'WTMREP37',
 'WTMREP38',
 'WTMREP39',
 'WTMREP40',
 'WTMREP41',
 'WTMREP42',
 'WTMREP43',
 'WTMREP44',
 'WTMREP45',
 'WTMREP46',
 'WTMREP47',
 'WTMREP48',
 'WTMREP49',
 'WTMREP50',
 'WTMREP51',
 'WTMREP52',
 'WTIREP01',
 'WTIREP02',
 'WTIREP03',
 'WTIREP04',
 'WTIREP05',
 'WTIREP06',
 'WTIREP07',
 'WTIREP08',
 'WTIREP09',
 'WTIREP10',
 'WTIREP11',
 'WTIREP12',
 'WTIREP13',
 'WTIREP14',
 'WTIREP15',
 'WTIREP16',
 'WTIREP17',
 'WTIREP18',
 'WTIREP19',
 'WTIREP20',
 'WTIREP21',
 'WTIREP22',
 'WTIREP23',
 'WTIREP24',
 'WTIREP25',
 'WTIREP26',
 'WTIREP27',
 'WTIREP28',
 'WTIREP29',
 'WTIREP30',
 'WTIREP31',
 'WTIREP32',
 'WTIREP33',
 'WTIREP34',
 'WTIREP35',
 'WTIREP36',
 'WTIREP37',
 'WTIREP38',
 'WTIREP39',
 'WTIREP40',
 'WTIREP41',
 'WTIREP42',
 'WTIREP43',
 'WTIREP44',
 'WTIREP45',
 'WTIREP46',
 'WTIREP47',
 'WTIREP48',
 'WTIREP49',
 'WTIREP50',
 'WTIREP51',
 'WTIREP52',
 'ELIGSTAT',
 'MORTSTAT',
 'UCOD_LEADING',
 'DIABETES',
 'HYPERTEN',
 'PERMTH_INT',
 'PERMTH_EXM']

In [10]:
everything_merged = pd.read_csv("merged_demo_mortality_caffeine.csv")

In [12]:
everything_merged.head()

,SEQN,WTSSCAF2,WTSSCAF4,SSMU1,SSMU1LC,SSMU3,SSMU3LC,SSMU4,SSMU4LC,SSMU5,...,WTIREP50,WTIREP51,WTIREP52,ELIGSTAT,MORTSTAT,UCOD_LEADING,DIABETES,HYPERTEN,PERMTH_INT,PERMTH_EXM
0,3.0,155825.292773,81908.618596,48.2,5.397605e-79,7.3,5.397605e-79,4.11,5.397605e-79,15.80,...,44480.987235,45389.112766,43781.905637,2,NaN,NaN,NaN,NaN,NaN,NaN
1,10.0,83707.269908,43060.890405,224.0,5.397605e-79,43.6,5.397605e-79,17.40,5.397605e-79,30.70,...,21725.159674,21625.081706,22539.031224,1,1.0,1.0,0.0,0.0,231.0,231.0
2,15.0,382453.382288,179126.737330,257.0,5.397605e-79,29.6,5.397605e-79,31.70,5.397605e-79,80.70,...,110186.143135,112750.496899,110008.647960,1,0.0,NaN,NaN,NaN,231.0,231.0
3,16.0,59345.928641,37637.555198,12.5,5.397605e-79,11.9,5.397605e-79,0.11,5.397605e-79,0.19,...,12284.984275,12183.762035,12917.307420,1,1.0,2.0,0.0,0.0,63.0,62.0
4,20.0,53884.837911,32614.899512,44.3,5.397605e-79,1.2,5.397605e-79,3.03,5.397605e-79,21.30,...,16066.523195,15921.677395,15921.677395,1,0.0,NaN,NaN,NaN,245.0,244.0

In [13]:
everything_merged.columns.tolist()

['SEQN',
 'WTSSCAF2',
 'WTSSCAF4',
 'SSMU1',
 'SSMU1LC',
 'SSMU3',
 'SSMU3LC',
 'SSMU4',
 'SSMU4LC',
 'SSMU5',
 'SSMU5LC',
 'SSMU6',
 'SSMU6LC',
 'SSMU7',
 'SSMU7LC',
 'SSMX1',
 'SSMX1LC',
 'SSMX2',
 'SSMX2LC',
 'SSMX3',
 'SSMX3LC',
 'SSMX4',
 'SSMX4LC',
 'SSMX5',
 'SSMX5LC',
 'SSMX6',
 'SSMX6LC',
 'SSMX7',
 'SSMX7LC',
 'SSAMU',
 'SSAMULC',
 'SDDSRVYR',
 'RIDSTATR',
 'RIDEXMON',
 'RIAGENDR',
 'RIDAGEYR',
 'RIDAGEMN',
 'RIDAGEEX',
 'RIDRETH1',
 'RIDRETH2',
 'DMQMILIT',
 'DMDBORN',
 'DMDCITZN',
 'DMDYRSUS',
 'DMDEDUC3',
 'DMDEDUC2',
 'DMDEDUC',
 'DMDSCHOL',
 'DMDMARTL',
 'DMDHHSIZ',
 'INDHHINC',
 'INDFMINC',
 'INDFMPIR',
 'RIDEXPRG',
 'RIDPREG',
 'DMDHRGND',
 'DMDHRAGE',
 'DMDHRBRN',
 'DMDHREDU',
 'DMDHRMAR',
 'DMDHSEDU',
 'WTINT2YR',
 'WTINT4YR',
 'WTMEC2YR',
 'WTMEC4YR',
 'SDMVPSU',
 'SDMVSTRA',
 'SDJ1REPN',
 'DMAETHN',
 'DMARACE',
 'WTMREP01',
 'WTMREP02',
 'WTMREP03',
 'WTMREP04',
 'WTMREP05',
 'WTMREP06',
 'WTMREP07',
 'WTMREP08',
 'WTMREP09',
 'WTMREP10',
 'WTMREP11',
 'WTMREP12',
 'WTMREP13',
 'WTMREP14',
 'WTMREP15',
 'WTMREP16',
 'WTMREP17',
 'WTMREP18',
 'WTMREP19',
 'WTMREP20',
 'WTMREP21',
 'WTMREP22',
 'WTMREP23',
 'WTMREP24',
 'WTMREP25',
 'WTMREP26',
 'WTMREP27',
 'WTMREP28',
 'WTMREP29',
 'WTMREP30',
 'WTMREP31',
 'WTMREP32',
 'WTMREP33',
 'WTMREP34',
 'WTMREP35',
 'WTMREP36',
 'WTMREP37',
 'WTMREP38',
 'WTMREP39',
 'WTMREP40',
 'WTMREP41',
 'WTMREP42',
 'WTMREP43',
 'WTMREP44',
 'WTMREP45',
 'WTMREP46',
 'WTMREP47',
 'WTMREP48',
 'WTMREP49',
 'WTMREP50',
 'WTMREP51',
 'WTMREP52',
 'WTIREP01',
 'WTIREP02',
 'WTIREP03',
 'WTIREP04',
 'WTIREP05',
 'WTIREP06',
 'WTIREP07',
 'WTIREP08',
 'WTIREP09',
 'WTIREP10',
 'WTIREP11',
 'WTIREP12',
 'WTIREP13',
 'WTIREP14',
 'WTIREP15',
 'WTIREP16',
 'WTIREP17',
 'WTIREP18',
 'WTIREP19',
 'WTIREP20',
 'WTIREP21',
 'WTIREP22',
 'WTIREP23',
 'WTIREP24',
 'WTIREP25',
 'WTIREP26',
 'WTIREP27',
 'WTIREP28',
 'WTIREP29',
 'WTIREP30',
 'WTIREP31',
 'WTIREP32',
 'WTIREP33',
 'WTIREP34',
 'WTIREP35',
 'WTIREP36',
 'WTIREP37',
 'WTIREP38',
 'WTIREP39',
 'WTIREP40',
 'WTIREP41',
 'WTIREP42',
 'WTIREP43',
 'WTIREP44',
 'WTIREP45',
 'WTIREP46',
 'WTIREP47',
 'WTIREP48',
 'WTIREP49',
 'WTIREP50',
 'WTIREP51',
 'WTIREP52',
 'ELIGSTAT',
 'MORTSTAT',
 'UCOD_LEADING',
 'DIABETES',
 'HYPERTEN',
 'PERMTH_INT',
 'PERMTH_EXM']