### PART 1: Wrangling and EDA

Demographic: https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/1999/DataFiles/DEMO.htm \
Mortality: https://www.cdc.gov/nchs/data/datalinkage/public-use-linked-mortality-file-description.pdf \
Caffeine: https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/1999/DataFiles/SSCAFE_A.htm

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [3]:
# Merge of mortality and demo into 'df'
mdf = pd.read_csv('linked_mortality_file_1999_2000.csv')
gdf = pd.read_sas("DEMO.xpt", format="xport")
df = gdf.merge(mdf, on="SEQN", how="inner")

### Description of Variables 

* ELIGSTAT (Eligibility Status for Mortality Follow-up): This variable shows whether or not a person is defined as eligible for mortality linkage due to insufficient identifying data. 
* MORTSTAT (Final Mortality Status): This variable determines the vital status of a participant and should be used when determining survival rates. Participants assumed alive are numbered 0 while while those assumed deceased are numbered 1. 
* PERMTH_INT (Number of Person Months of Follow-Up from NHANES Interview Date): This variable describes the number of person-months of the follow up from the interview date. 
* RIDAGEEX: This variable describes the age in months at the time the participant took the MEC exam. This data is only provided for those who were less than 85 years old at the time of the household screening interview.

In [4]:
# Merge of df and caffeine dataset
cdf = pd.read_sas("SSCAFE_A.xpt", format="xport")
merged_df = cdf.merge(df, on="SEQN", how="inner")

**ANSWER** Explain rationale for choosing this dataset

**ANSWER** Document any missing values here

In [13]:
# Choosing variables of interest
cols = ["SEQN", "ELIGSTAT", "MORTSTAT", "PERMTH_INT", "RIDAGEEX", "RIAGENDR",
        "WTSSCAF2", "WTSSCAF4", "SSMX1", "SSMX1LC","SSMX2", "SSMX2LC","SSMX3", "SSMX3LC",
        "SSMX4", "SSMX4LC", "SSMX5", "SSMX5LC", "SSMX6", "SSMX6LC",
        "SSMX7", "SSMX7LC"]
new_df = merged_df[cols].copy()
new_df.to_csv("working_df.csv", index=False)
pd.set_option('display.max_columns', None)
new_df.head()

,SEQN,ELIGSTAT,MORTSTAT,PERMTH_INT,RIDAGEEX,RIAGENDR,WTSSCAF2,WTSSCAF4,SSMX1,SSMX1LC,SSMX2,SSMX2LC,SSMX3,SSMX3LC,SSMX4,SSMX4LC,SSMX5,SSMX5LC,SSMX6,SSMX6LC,SSMX7,SSMX7LC
0,3.0,2,NaN,NaN,126.0,2.0,155825.292773,81908.618596,30.80,5.397605e-79,20.10,5.397605e-79,45.40,5.397605e-79,0.95,5.397605e-79,10.900,5.397605e-79,11.80,5.397605e-79,0.63,5.397605e-79
1,10.0,1,1.0,231.0,518.0,1.0,83707.269908,43060.890405,116.00,5.397605e-79,61.70,5.397605e-79,130.00,5.397605e-79,1.53,5.397605e-79,18.700,5.397605e-79,17.30,5.397605e-79,1.25,5.397605e-79
2,15.0,1,0.0,231.0,460.0,2.0,382453.382288,179126.737330,208.00,5.397605e-79,86.90,5.397605e-79,177.00,5.397605e-79,4.96,5.397605e-79,52.200,5.397605e-79,48.90,5.397605e-79,4.28,5.397605e-79
3,16.0,1,1.0,63.0,NaN,2.0,59345.928641,37637.555198,1.44,5.397605e-79,16.80,5.397605e-79,21.20,5.397605e-79,0.02,1.000000e+00,0.072,5.397605e-79,5.75,5.397605e-79,0.04,1.000000e+00
4,20.0,1,0.0,245.0,286.0,2.0,53884.837911,32614.899512,41.50,5.397605e-79,3.34,5.397605e-79,8.73,5.397605e-79,1.48,5.397605e-79,28.300,5.397605e-79,4.42,5.397605e-79,2.68,5.397605e-79

### EDA and visualization bomboclat blow

In [6]:
# copy paste of stuff yas
print("h")

h

Based off EDA
**ANSWER**
1) Are any important variables skewed? 
2) Are there outliers? 
3) How correlated are pairs of variables? 
4) Do pairs of categorical variables exhibit interesting patterns in contingency tables? 
5) Provide a clear discussion and examination of the data and the variables you are interested in using

### Part 2: KNN Classification/Regression

1) Describe the data, particularly what an observation is and whether there are any missing data that might impact your analysis. Who collected the data and why? What known limitations are there to analysis? (10/100 pts)\
**The dataset is made up of a few important columns, namely the sequence number (SEQN), the eligibility status (ELIGSTAT), the death status (MORTSTAT). It also includes the demographic variables such as age (in months) and gender (1 = male, 2 = female). Included is also a few variables from the caffeine dataset including the representative weight (we are using WTSSCAF2 since we are looking at 1 cycle from 1999-2000), and several metabolites SSMX1-7 along wit their LC (lab comment version). We are looking at SSMX1 specifically because it represents how much caffeine an individual was exposed to. We ignore the LC version during regression**\
**There are sme missing data. Particularly, there are 942 missing data from the mortality status column out of 2648, which need to be removed before we can regress on it. There are also 53 missing ages, which isn't particularly important so we can either keep or remove it. In addition, for each of the caffeine metabolites, there are 592 values missing out of 2648. Since we are looking at the relationship between SSMX1 and death, we need to drop these NA's.** \
**The data was collected by NHANES to see if there is a broader implicaton of consumption of caffeine on the health of the general public. Caffeine is so accessible and many people consume it daily. The data is collected through random sampling and use of physical exams and urine samples in this dataset.**\
**There are several limitations. First, we are looking at caffeine intake at a singular point in time, not over the course of a long time. Therefore, we may not be able to say that long-term habitual caffeine consumption is linked to death. In addition, we do not take into consideration any confounding variables like presdispositions, prior health issues, and anything beyond age and sex.**

In [14]:
print(new_df.shape)
new_df.isna().sum()

(2648, 22)

SEQN            0
ELIGSTAT        0
MORTSTAT      942
PERMTH_INT    942
RIDAGEEX       53
RIAGENDR        0
WTSSCAF2        0
WTSSCAF4        0
SSMX1         592
SSMX1LC       592
SSMX2         592
SSMX2LC       592
SSMX3         592
SSMX3LC       592
SSMX4         592
SSMX4LC       592
SSMX5         592
SSMX5LC       592
SSMX6         592
SSMX6LC       592
SSMX7         592
SSMX7LC       592
dtype: int64

In [7]:
new_df.describe()

,SEQN,ELIGSTAT,MORTSTAT,PERMTH_INT,RIDAGEEX,RIAGENDR,WTSSCAF2,WTSSCAF4,SSMX4,SSMX4LC,SSMX5,SSMX5LC,SSMX6,SSMX6LC,SSMX7,SSMX7LC
count,2648.000000,2648.000000,1706.000000,1706.000000,2595.000000,2648.000000,2.648000e+03,2.648000e+03,2056.000000,2.056000e+03,2056.000000,2.056000e+03,2056.000000,2.056000e+03,2056.000000,2.056000e+03
mean,5015.427870,1.356495,0.297186,205.650059,405.627746,1.524169,9.387972e+04,4.523310e+04,2.651804,5.496109e-02,18.545646,1.410506e-02,30.624553,3.404669e-03,4.470822,1.021401e-01
std,2874.909231,0.480629,0.457153,63.690242,268.712502,0.499510,1.173340e+05,5.455318e+04,11.301862,2.279597e-01,21.345290,1.179528e-01,45.806068,5.826430e-02,6.789654,3.029061e-01
min,3.000000,1.000000,0.000000,1.000000,72.000000,1.000000,5.397605e-79,5.397605e-79,0.020000,5.397605e-79,0.005000,5.397605e-79,0.010000,5.397605e-79,0.040000,5.397605e-79
25%,2534.000000,1.000000,0.000000,212.250000,179.500000,1.000000,8.547617e+03,5.138477e+03,0.380000,5.397605e-79,3.260000,5.397605e-79,5.487500,5.397605e-79,0.397500,5.397605e-79
50%,4914.500000,1.000000,0.000000,235.000000,321.000000,2.000000,3.597306e+04,1.882514e+04,1.250000,5.397605e-79,11.500000,5.397605e-79,15.300000,5.397605e-79,1.910000,5.397605e-79
75%,7565.000000,2.000000,1.000000,242.000000,613.500000,2.000000,1.545717e+05,7.293606e+04,2.820000,5.397605e-79,26.100000,5.397605e-79,36.725000,5.397605e-79,5.672500,5.397605e-79
max,9961.000000,3.000000,1.000000,249.000000,1018.000000,2.000000,9.091403e+05,3.577499e+05,341.000000,1.000000e+00,172.000000,1.000000e+00,791.000000,1.000000e+00,60.800000,1.000000e+00

2) Natalie

3) Rashi

4. Ashley

5. Angel